import { ArrowRight } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Link, Navigate, useNavigate, useSearchParams } from "react-router-dom";
import { useLearningSession } from "../components/LearningSession";
import { learningRequest } from "../infrastructure/learningClient";
import { LanguageSwitcher, useLocale, uiText } from "../i18n";

import { Brand } from "../components/Brand";
import { AuraScene } from "../components/AuraPrimitives";

export function safeReturnPath(value: string | null) { return value && /^\/(?!\/)/.test(value) && !value.includes("\\") && !value.startsWith("/sign-in") ? value : "/"; }

export function SignInPage() {
  const { session, refresh } = useLearningSession();
  const { locale } = useLocale(); const t=(zh:string,en:string)=>uiText(locale,zh,en);
  const navigate=useNavigate(); const [params]=useSearchParams(); const next=safeReturnPath(params.get("next"));
  const [register,setRegister]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  if(session?.authenticated)return <Navigate to={next} replace/>;
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await learningRequest(`auth/${register?"register":"login"}`,{email:email.trim(),password,...(register?{name}: {})});sessionStorage.removeItem("ceptlens.visitor-entry.v1");await refresh();navigate(next,{replace:true});}catch(e){const message=e instanceof Error?e.message:"";const translations:Record<string,string>={"邮箱或密码不正确。":"The email or password is incorrect.","该邮箱已注册。":"This email already has an account. Please sign in.","注册信息无效。":"Use a valid email and a password of 10–200 characters."};setError(locale==="en-US"?(translations[message]??message):message);}finally{setBusy(false);}}
  return <div className="welcome-page"><header className="welcome-header"><Link to="/" className="welcome-brand" aria-label={t("CeptLens 首页","CeptLens home")}><Brand/></Link><LanguageSwitcher/></header><main className="welcome-grid"><aside className="welcome-art" aria-label={t("CeptLens 交互式学习", "CeptLens interactive learning")}><AuraScene compact paused/><div className="welcome-art-copy"><h1>{t("让每一次追问，", "Every good question.")}<br/>{t("都有新的理解。", "A new understanding.")}</h1><p>Seize understanding.</p></div></aside><section className="welcome-form-card"><h2>{register?t("创建你的账户","Create your account"):t("欢迎回来","Welcome back")}</h2><div className="auth-mode-tabs" role="group" aria-label={t("账户操作","Account action")}><button aria-pressed={!register} onClick={()=>{setRegister(false);setError("");}}>{t("登录","Sign in")}</button><button aria-pressed={register} onClick={()=>{setRegister(true);setError("");}}>{t("注册","Sign up")}</button></div><form onSubmit={submit} className="welcome-form">{register&&<label>{t("显示名","Display name")}<input autoComplete="nickname" required maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder={t("我们该如何称呼你？","What should we call you?")}/></label>}<label>{t("邮箱","Email")}<input type="email" autoComplete="username" required maxLength={200} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>{t("密码","Password")}<input type="password" autoComplete={register?"new-password":"current-password"} required minLength={register?10:1} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} placeholder={register?t("至少 10 个字符","At least 10 characters"):t("输入密码","Your password")}/></label>{error&&<p role="alert" className="service-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy?t("处理中…","Working…"):register?t("创建账户","Create account"):t("登录","Sign in")}<ArrowRight size={17}/></button></form><div className="visitor-divider"><span>{t("或","or")}</span></div><button className="visitor-button" onClick={()=>{sessionStorage.setItem("ceptlens.visitor-entry.v1","true");navigate(next,{replace:true});}}>{t("以访客身份进入","Continue as visitor")}<ArrowRight size={16}/></button><p className="visitor-note">{t("无需注册，即可探索题目与词条。","Explore questions and concepts without an account.")}</p></section></main></div>;
}
