import { expect, it, vi } from "vitest";
import { ensureDependencies, transientInstallFailure } from "./dependency-readiness.mjs";
function fixture(overrides = {}) { return { installed: vi.fn().mockResolvedValue(true), probe: vi.fn().mockResolvedValue(), install: vi.fn().mockResolvedValue({ code: 0, output: "ok" }), wait: vi.fn().mockResolvedValue(), report: vi.fn(), ...overrides }; }
it("probes existing dependencies rather than trusting package folders", async () => { const f = fixture(); expect(await ensureDependencies(f)).toBe("existing"); expect(f.probe).toHaveBeenCalledOnce(); expect(f.install).not.toHaveBeenCalled(); });
it("repairs native modules that have package metadata but cannot run", async () => { const f = fixture({ probe: vi.fn().mockRejectedValueOnce(new Error("missing native binary")).mockResolvedValue() }); expect(await ensureDependencies(f)).toBe("installed"); expect(f.install).toHaveBeenCalledOnce(); });
it("automatically retries a transient first installation only when still unusable", async () => { const f = fixture({ installed: vi.fn().mockResolvedValueOnce(false).mockResolvedValueOnce(false).mockResolvedValue(true), install: vi.fn().mockResolvedValueOnce({ code: 1, output: "npm error EBUSY rename" }).mockResolvedValue({ code: 0, output: "ok" }) }); await ensureDependencies(f); expect(f.install).toHaveBeenCalledTimes(2); expect(f.wait).toHaveBeenCalledOnce(); });
it("does not hide an unknown npm failure when dependencies remain missing", async () => { const f = fixture({ installed: vi.fn().mockResolvedValue(false), install: vi.fn().mockResolvedValue({ code: 1, output: "unknown lifecycle failure" }) }); await expect(ensureDependencies(f)).rejects.toThrow("npm 安装失败"); expect(f.install).toHaveBeenCalledOnce(); });
it("continues on the first launch when npm failed but all required tools are ready", async () => { const f = fixture({ installed: vi.fn().mockResolvedValueOnce(false).mockResolvedValue(true), install: vi.fn().mockResolvedValue({ code: 1, output: "cleanup failed" }) }); expect(await ensureDependencies(f)).toBe("usable-with-warning"); expect(f.probe).toHaveBeenCalledOnce(); expect(f.install).toHaveBeenCalledOnce(); expect(f.wait).not.toHaveBeenCalled(); expect(f.report).toHaveBeenCalledWith(expect.stringContaining("继续启动")); });
it("does not run another installation on a later healthy startup", async () => { const f = fixture(); expect(await ensureDependencies(f)).toBe("existing"); expect(f.install).not.toHaveBeenCalled(); });
it("rejects repeated transient failures instead of looping", async () => { const f = fixture({ installed: vi.fn().mockResolvedValue(false), install: vi.fn().mockResolvedValue({ code: 1, output: "npm error ECONNRESET" }) }); await expect(ensureDependencies(f)).rejects.toThrow("npm 安装失败"); expect(f.install).toHaveBeenCalledTimes(2); });
it("npm success still requires runnable tools", async () => { const f = fixture({ probe: vi.fn().mockRejectedValue(new Error("tool failure")) }); await expect(ensureDependencies(f)).rejects.toThrow("运行检查仍未通过"); });
it("a failed install with package metadata but broken tools must still stop", async () => { const f = fixture({ installed: vi.fn().mockResolvedValueOnce(false).mockResolvedValue(true), probe: vi.fn().mockRejectedValue(new Error("missing native addon")), install: vi.fn().mockResolvedValue({ code: 1, output: "unknown error" }) }); await expect(ensureDependencies(f)).rejects.toThrow("依赖尚不可用"); });
it("retries network or file contention errors, not permission/configuration/auth errors generally", () => { expect(transientInstallFailure("npm error ETIMEDOUT")).toBe(true); for (const message of ["npm error E401", "npm error EBADENGINE", "npm error EACCES", "unknown failure"]) expect(transientInstallFailure(message)).toBe(false); });
